#!/usr/bin/env node
// Stamp sw.js's BUILD with a CONTENT HASH of app.html.
//
// WHY THIS EXISTS: the service worker ships an update only when sw.js is byte-different. If
// app.html is edited without bumping BUILD, sw.js is identical, the browser sees no new worker,
// and the phone keeps serving the CACHED old app forever — the fix is live on the server but
// never reaches the user. That failure is silent and looks exactly like "the fix didn't work".
//
// Hashing app.html removes the human step: any change to app.html changes the hash, so the SW
// always detects a real change — and never a fake one.
const fs = require('fs'), crypto = require('crypto'), path = require('path');
const root = path.join(__dirname, '..');
const appPath = path.join(root, 'app.html'), swPath = path.join(root, 'sw.js');

let app = fs.readFileSync(appPath, 'utf8');
const ver = (app.match(/APP_VERSION = '(v\d+)'/) || [])[1];
if (!ver) { console.error('FAIL: no APP_VERSION found in app.html'); process.exit(1); }

const hash = crypto.createHash('sha256').update(app).digest('hex').slice(0, 8);
let sw = fs.readFileSync(swPath, 'utf8');
const before = (sw.match(/BUILD = '([^']+)'/) || [])[1];
const stamp = `${ver}-${hash}`;
if (before !== stamp) {
  sw = sw.replace(/BUILD = '[^']+'/, `BUILD = '${stamp}'`);
  fs.writeFileSync(swPath, sw);
}

// The SERVER stamp answers a DIFFERENT question and therefore needs a different hash.
//
// sw.js BUILD answers "does the phone need to re-download the app?" — so it hashes app.html
// alone. Adding the backend to it would make every backend-only deploy push a fresh ~196KB
// app.html download to every phone for no reason, which on a slow line is exactly the stall
// v309 was written to end.
//
// api/_build.js answers "is the deployed BACKEND current?" — and until v637 it reused the
// app.html-only stamp, so a backend-only deploy produced an identical value and `curl
// /api/health` could not tell old code from new. The silent-skip checklist listed that as fixed;
// it was not. Today's change was backend-only and would have been unverifiable. So the server
// stamp now also carries a hash of every api/*.js file.
const apiDir = path.join(root, 'api');
const apiFiles = [];
(function walk(d) {
  for (const e of fs.readdirSync(d, { withFileTypes: true }).sort((a, b) => a.name < b.name ? -1 : 1)) {
    const p = path.join(d, e.name);
    if (e.isDirectory()) walk(p);
    // _build.js itself is excluded: it is written FROM this hash, so including it could never settle.
    else if (e.name.endsWith('.js') && p !== path.join(apiDir, '_build.js')) apiFiles.push(p);
  }
})(apiDir);
const apiHash = crypto.createHash('sha256')
  .update(apiFiles.map(p => path.relative(root, p) + '\0' + fs.readFileSync(p, 'utf8')).join('\0'))
  .digest('hex').slice(0, 8);

const serverStamp = `${stamp}+api.${apiHash}`;
const buildPath = path.join(apiDir, '_build.js');
const want = `// AUTO-GENERATED by scripts/stamp-build.js — do not edit by hand.\nmodule.exports = '${serverStamp}';\n`;
const prevServer = fs.existsSync(buildPath)
  ? (fs.readFileSync(buildPath, 'utf8').match(/'([^']+)'/) || [])[1] : null;
if (prevServer !== serverStamp) fs.writeFileSync(buildPath, want);

console.log(before === stamp ? `BUILD already current: ${stamp}` : `BUILD ${before}  ->  ${stamp}   (hash of app.html)`);
console.log(prevServer === serverStamp
  ? `server stamp already current: ${serverStamp}`
  : `server ${prevServer || '(none)'}  ->  ${serverStamp}   (+ hash of ${apiFiles.length} api files)`);
console.log(`stamped: sw.js + api/_build.js`);
